language: android

android:
  components:
    - tools
    - platform-tools
    - tools
    - android-27

jdk:
  - oraclejdk8

notifications:
  email: false

script:
  - ./gradlew assemble check
  - ./gradlew checkstyle
